# Generated by Django 5.0.6 on 2024-06-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='radius',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
