# Generated by Django 4.2.3 on 2024-07-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_event_url_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geolocation',
        ),
    ]
